<?php

namespace BackendBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArticleQBTitre($idUser)
    {

        $query = $this->getEntityManager()
             ->createQuery("SELECT a FROM BackendBundle:Reclamation a 
                                 where a.idUser like :idUser 
                                 ORDER BY  a.priority ASC ")
             ->setParameter('idUser','%'.$idUser.'%');
         return $query->getResult();
    }
}
