agentgestionnaire:
    path:     /agentgestionnaire
    defaults: { _controller: BackendBundle:Default:index }
backend_fournisseur:
    resource: "@BackendBundle/Resources/config/routing/fournisseur.yml"
    prefix:   /f

backend_matriel:
    resource: "@BackendBundle/Resources/config/routing/matriel.yml"
    prefix:   /matriels

backend_besoin_createOne:
    path: /besoin/create/1
    defaults: { _controller: BackendBundle:Besoin:createOne }

add_besoin:
    path: /besoin/add
    defaults: { _controller: BackendBundle:Besoin:addBesoin }

add_product:
    path: /add
    defaults: { _controller: BackendBundle:Product:add }

recupererpass:
    path: /confirmmail
    defaults: { _controller: BackendBundle:Default:confirm }

changerpass:
    path: /changerpass
    defaults: { _controller: BackendBundle:Default:update }

list_product:
    path: /list
    defaults: { _controller: BackendBundle:Product:list }
detailedpost:
    path: /detail
    defaults: { _controller: BackendBundle:Product:show }
search:
    path:     /search
    defaults: { _controller: BackendBundle:Product:search }
staff_new:
    path: /addstaff
    defaults: { _controller: BackendBundle:Staff:new }
staff_edit:
    path: /staff_edit/{id}
    defaults: { _controller: BackendBundle:Staff:edit }
staff_show:
    path: /staff_show/{id}
    defaults: { _controller: BackendBundle:Staff:show }

staff_delete:
    path: /staff_delete/{id}
    defaults: { _controller: BackendBundle:Staff:delete }
staff_index:
    path:     /liststaff
    defaults: { _controller: "BackendBundle:Staff:index" }
reservermatriel_index:
    path:     /listreservation
    defaults: { _controller: "BackendBundle:ReserverMatriel:index" }
reservermatriel_show:
    path:     /showreservation/{id}
    defaults: { _controller: "BackendBundle:ReserverMatriel:show" }
reservermatriel_edit:
     path:     /editreservation/{id}
     defaults: { _controller: "BackendBundle:ReserverMatriel:edit" }
reservermatriel_delete:
     path:     /deletereservation/{id}
     defaults: { _controller: "BackendBundle:ReserverMatriel:delete" }
     methods:  DELETE
reservermatriel_new:
     path:     /addreservation
     defaults: { _controller: "BackendBundle:ReserverMatriel:new" }
index_achat:
    path: /achats
    defaults: { _controller: BackendBundle:Achat:index}
read_achat:
    path: /ttachats
    defaults: { _controller: BackendBundle:Achat:read}
index_achat_show:
    path: /achats/show/{id}
    defaults: { _controller: BackendBundle:Achat:detailsProduit}
add_achat:
    path: /achats/add/{id}
    defaults: { _controller: BackendBundle:Achat:addAchat}
panier_achat:
    path: /achats/panier
    defaults: { _controller: BackendBundle:Achat:panier}
delete_achat:
    path: /achats/panier/delete/{id}
    defaults: { _controller: BackendBundle:Achat:delete}
edit_achat:
    path: /achats/panier/edit/{id}
    defaults: { _controller: BackendBundle:Achat:edit}
confirm_achat:
    path: /achats/panier/confirm
    defaults: { _controller: BackendBundle:Achat:confirm}
commande_achat:
    path: /achats/commandes
    defaults: { _controller: BackendBundle:Achat:commandes}
backend_besoin_createOne:
    path: /besoin/create/1
    defaults: { _controller: BackendBundle:Besoin:createOne }
add_besoin:
    path: /besoin/add
    defaults: { _controller: BackendBundle:Besoin:addBesoin }
add_besoin_product:
    path: /besoin/add/product
    defaults: { _controller: BackendBundle:Besoin:addBesoinProduct }
step2:
    path:     /{id}/step2
    defaults: { _controller: BackendBundle:Besoin:createTwo }
delete_prod_besoin:
    path:     /besoin/delete/{id}/{idb}
    defaults: { _controller: BackendBundle:Besoin:deleteProdBesoin}
edit_prod_besoin:
    path:     /besoin/edit/{id}/{idb}
    defaults: { _controller: BackendBundle:Besoin:editProdBesoin}
edit_product_besoin:
    path:     /besoin/edit/product
    defaults: { _controller: BackendBundle:Besoin:editProductBesoin}
index_besoins:
    path: /besoins
    defaults: { _controller: BackendBundle:Besoin:index}
read_besoin:
    path: /besoins/show/{id}
    defaults: { _controller: BackendBundle:Besoin:show}
delete_besoin:
    path: /besoin/delete/{id}
    defaults: { _controller: BackendBundle:Besoin:delete}
edit_besoin:
    path: /besoin/edit/{id}
    defaults: { _controller: BackendBundle:Besoin:edit}
trait_besoin:
    path: /besoin/edit/trait
    defaults: { _controller: BackendBundle:Besoin:edittrait}
pdf_generate:
    path: /besoin/pdf/{id}
    defaults: { _controller: BackendBundle:Besoin:pdf}
pdf_generate_achat:
    path: /achat/pdf/{id}
    defaults: { _controller: BackendBundle:Achat:pdf}
add_cmd:
    path: /cmd/add
    defaults: { _controller: BackendBundle:Commande:addCmd}
add_cmd_trait:
    path: /cmd/add/trait
    defaults: { _controller: BackendBundle:Commande:addCmdTrait}
index_cmd:
    path: /cmds
    defaults: { _controller: BackendBundle:Commande:index}
delete_cmd:
    path: /delete/cmd/{id}
    defaults: { _controller: BackendBundle:Commande:delete}
edit_cmd:
    path: /edit/cmd/{id}/{f}
    defaults: { _controller: BackendBundle:Commande:edit}
edit_cmd_trait:
    path: /edit/cmd/trait
    defaults: { _controller: BackendBundle:Commande:editCmd}
delete_cmd_besoin:
    path: /delete/cmd/besoin/{id}/{f}
    defaults: { _controller: BackendBundle:Commande:deleteCmdBesoin}
